### ISSUE TITLE
Ontology scripts handling

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-webpage#15]
I was wondering if there is a way to rewrite/rewire how we deal with ontology-specific scripts because:

a) the current handling is clunky in general,
b) now that `apis-webpage` has its own repo, it seems kind of counter-intuitive to continue to be reliant on a file contained within here for one-off execution of code that's part of `apis-ontologies`.

Quick rundown for those unfamiliar with what running scripts entails:
* scripts unique to an ontology are meant to be put in a project's `ontology_specific_scripts` subfolder,
* they are executed from `apis-rdf-devops` via ` python manage.py run_ontology_script SCRIPT_NAME`,
* `run_ontology_script` is [a management command which is part of this repo](https://github.com/acdh-oeaw/apis-webpage/blob/dev/webpage/management/commands/run_ontology_script.py), `apis-webpage`, which ingests the script.

Due to this setup, we cannot pass arguments to our scripts and we can't make use of output formatting options available to management commands. The main logic has to happen in `run()`, which either ends up a bloated mess which does everything, or from which we have to pass the same stuff around all the time to helper functions.

For examples, see [this branch](https://gitlab.oeaw.ac.at/acdh-ch/frischmuth/backend/apis-ontologies/-/tree/frischmuth/data_import_scripts/frischmuth/ontology_specific_scripts) over on GitLab (still missing: latest changes from our working branch).

**Comment by b1rger** [comment]
Yes, the `run_ontology_script` management command is not useful. You can put a `start.sh` in your ontology folder and use this to run any command you like: https://github.com/acdh-oeaw/apis-rdf-devops/blob/658fb1a266745ea93821b0b4c79d4cd68a352ccc/start.sh#L15

**Comment by koeaw** [comment]
But the `start.sh` script is meant for auto-running stuff on deployment, right?

What we need is a way to selectively run Python scripts on already deployed instances. So in that regard, `run_ontology_script` works as intended, but the location where it's saved doesn't make sense (anymore) and it limits us in what we can do with it.

Would Django be able to find our scripts if we put them in a separate `management > commands` folder inside our project folder and rewrote them to be proper management commands?

**Comment by sennierer** [comment]
should work to just put management commands in the ontologies module
