### ISSUE TITLE
Drop fundament.css

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-webpage#34]
The fundament code is buggy - we already the problem with the burger menu that is not visible on mobile devices and I just realized the `<dialog>` element is set to `block` by fundament, which makes it visible by default - but it should be [hidden by default and only show up when triggered](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog).

I suggest to drop `fundament.css` - the look and feel does not change that much.

Please @acdh-oeaw/prosnet , test your project without this css file included. You only have to go to your `webpage/base.html` and remove the `styles` block starting in line 15: 
https://github.com/acdh-oeaw/apis-webpage/blob/9e5334513576c533bce64669129895eb62818dfd/webpage/templates/webpage/base.html#L15

**Comment by sennierer** [comment]
decided to remove fundament
